import { z } from 'zod'

const clientSchema = z.object({
  NEXT_PUBLIC_APP_NAME: z.string().optional(),
  NEXT_PUBLIC_APP_DESCRIPTION: z.string().optional(),
  NEXT_PUBLIC_APP_URL: z.string().url().optional(),
  NEXT_PUBLIC_CONVEX_URL: z.string().url().optional(),
  NEXT_PUBLIC_THIRDWEB_CLIENT_ID: z.string().optional(),
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: z.string().optional(),
  NEXT_PUBLIC_ADMIN_WALLET_ADDRESSES: z.string().optional(),
  NEXT_PUBLIC_SUBSCRIPTION_MANAGER_ADDRESS: z.string().optional(),
  NEXT_PUBLIC_SUBSCRIPTION_CHAIN_ID: z.coerce.number().optional(),
  NEXT_PUBLIC_SUBSCRIPTION_BASE_PRICE_WEI: z.string().optional(),
  NEXT_PUBLIC_SUBSCRIPTION_PLUS_PRICE_WEI: z.string().optional(),
  NEXT_PUBLIC_MEZO_TESTNET_CHAIN_ID: z.coerce.number().optional(),
  NEXT_PUBLIC_MEZO_TESTNET_RPC_URL: z.string().url().optional(),
  NEXT_PUBLIC_MEZO_TESTNET_EXPLORER_URL: z.string().url().optional(),
  NEXT_PUBLIC_X402_NETWORK: z.string().optional(),
  NEXT_PUBLIC_WALLET_PROVIDER: z
    .enum(['thirdweb', 'rainbow-kit', 'rainbowkit'])
    .optional()
})

export const envClient = clientSchema.parse({
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_APP_DESCRIPTION: process.env.NEXT_PUBLIC_APP_DESCRIPTION,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,
  NEXT_PUBLIC_THIRDWEB_CLIENT_ID: process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID,
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:
    process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID,
  NEXT_PUBLIC_ADMIN_WALLET_ADDRESSES:
    process.env.NEXT_PUBLIC_ADMIN_WALLET_ADDRESSES,
  NEXT_PUBLIC_SUBSCRIPTION_MANAGER_ADDRESS:
    process.env.NEXT_PUBLIC_SUBSCRIPTION_MANAGER_ADDRESS,
  NEXT_PUBLIC_SUBSCRIPTION_CHAIN_ID:
    process.env.NEXT_PUBLIC_SUBSCRIPTION_CHAIN_ID,
  NEXT_PUBLIC_SUBSCRIPTION_BASE_PRICE_WEI:
    process.env.NEXT_PUBLIC_SUBSCRIPTION_BASE_PRICE_WEI,
  NEXT_PUBLIC_SUBSCRIPTION_PLUS_PRICE_WEI:
    process.env.NEXT_PUBLIC_SUBSCRIPTION_PLUS_PRICE_WEI,
  NEXT_PUBLIC_MEZO_TESTNET_CHAIN_ID:
    process.env.NEXT_PUBLIC_MEZO_TESTNET_CHAIN_ID,
  NEXT_PUBLIC_MEZO_TESTNET_RPC_URL:
    process.env.NEXT_PUBLIC_MEZO_TESTNET_RPC_URL,
  NEXT_PUBLIC_MEZO_TESTNET_EXPLORER_URL:
    process.env.NEXT_PUBLIC_MEZO_TESTNET_EXPLORER_URL,
  NEXT_PUBLIC_X402_NETWORK: process.env.NEXT_PUBLIC_X402_NETWORK,
  NEXT_PUBLIC_WALLET_PROVIDER: process.env.NEXT_PUBLIC_WALLET_PROVIDER
})
