import { z } from 'zod'

const optionalString = z.preprocess(
  value => (value === '' ? undefined : value),
  z.string().optional()
)

const optionalUrl = z.preprocess(
  value => (value === '' ? undefined : value),
  z.string().url().optional()
)

const optionalNumber = z.preprocess(
  value => (value === '' ? undefined : value),
  z.coerce.number().optional()
)

const optionalBoolean = z.preprocess(value => {
  if (value === '') {
    return undefined
  }

  if (typeof value === 'string') {
    return value === 'true'
  }

  return value
}, z.boolean().optional())

const clientSchema = z.object({
  NEXT_PUBLIC_APP_NAME: optionalString,
  NEXT_PUBLIC_APP_DESCRIPTION: optionalString,
  NEXT_PUBLIC_APP_URL: optionalUrl,
  NEXT_PUBLIC_CONVEX_URL: optionalUrl,
  NEXT_PUBLIC_THIRDWEB_CLIENT_ID: optionalString,
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: optionalString,
  NEXT_PUBLIC_ADMIN_WALLET_ADDRESSES: optionalString,
  NEXT_PUBLIC_SUBSCRIPTION_MANAGER_ADDRESS: optionalString,
  NEXT_PUBLIC_AGENT_ATTESTOR_ADDRESS: optionalString,
  NEXT_PUBLIC_AGENT_RUN_VAULT_ADDRESS: optionalString,
  NEXT_PUBLIC_SUBSCRIPTION_CHAIN_ID: optionalNumber,
  NEXT_PUBLIC_SUBSCRIPTION_BASE_PRICE_WEI: optionalString,
  NEXT_PUBLIC_SUBSCRIPTION_PLUS_PRICE_WEI: optionalString,
  NEXT_PUBLIC_EVM_CHAIN_ID: optionalNumber,
  NEXT_PUBLIC_EVM_CHAIN_NAME: optionalString,
  NEXT_PUBLIC_EVM_CHAIN_SHORT_NAME: optionalString,
  NEXT_PUBLIC_EVM_RPC_URL: optionalUrl,
  NEXT_PUBLIC_EVM_EXPLORER_NAME: optionalString,
  NEXT_PUBLIC_EVM_EXPLORER_URL: optionalUrl,
  NEXT_PUBLIC_EVM_NATIVE_CURRENCY_NAME: optionalString,
  NEXT_PUBLIC_EVM_NATIVE_CURRENCY_SYMBOL: optionalString,
  NEXT_PUBLIC_EVM_NATIVE_CURRENCY_DECIMALS: optionalNumber,
  NEXT_PUBLIC_EVM_IS_TESTNET: optionalBoolean,
  NEXT_PUBLIC_X402_NETWORK: optionalString,
  NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS: optionalString,
  NEXT_PUBLIC_PAYMENT_TOKEN_NAME: optionalString,
  NEXT_PUBLIC_PAYMENT_TOKEN_SYMBOL: optionalString,
  NEXT_PUBLIC_PAYMENT_TOKEN_LABEL: optionalString,
  NEXT_PUBLIC_PAYMENT_TOKEN_VERSION: optionalString,
  NEXT_PUBLIC_PAYMENT_TOKEN_DECIMALS: optionalNumber,
  NEXT_PUBLIC_PAYMENT_TOKEN_TRANSFER_METHOD: optionalString,
  NEXT_PUBLIC_WALLET_PROVIDER: z.preprocess(
    value => (value === '' ? undefined : value),
    z.enum(['thirdweb', 'rainbow-kit', 'rainbowkit']).optional()
  )
})

export const envClient = clientSchema.parse({
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_APP_DESCRIPTION: process.env.NEXT_PUBLIC_APP_DESCRIPTION,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,
  NEXT_PUBLIC_THIRDWEB_CLIENT_ID: process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID,
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:
    process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID,
  NEXT_PUBLIC_ADMIN_WALLET_ADDRESSES:
    process.env.NEXT_PUBLIC_ADMIN_WALLET_ADDRESSES,
  NEXT_PUBLIC_SUBSCRIPTION_MANAGER_ADDRESS:
    process.env.NEXT_PUBLIC_SUBSCRIPTION_MANAGER_ADDRESS,
  NEXT_PUBLIC_AGENT_ATTESTOR_ADDRESS:
    process.env.NEXT_PUBLIC_AGENT_ATTESTOR_ADDRESS,
  NEXT_PUBLIC_AGENT_RUN_VAULT_ADDRESS:
    process.env.NEXT_PUBLIC_AGENT_RUN_VAULT_ADDRESS,
  NEXT_PUBLIC_SUBSCRIPTION_CHAIN_ID:
    process.env.NEXT_PUBLIC_SUBSCRIPTION_CHAIN_ID,
  NEXT_PUBLIC_SUBSCRIPTION_BASE_PRICE_WEI:
    process.env.NEXT_PUBLIC_SUBSCRIPTION_BASE_PRICE_WEI,
  NEXT_PUBLIC_SUBSCRIPTION_PLUS_PRICE_WEI:
    process.env.NEXT_PUBLIC_SUBSCRIPTION_PLUS_PRICE_WEI,
  NEXT_PUBLIC_EVM_CHAIN_ID: process.env.NEXT_PUBLIC_EVM_CHAIN_ID,
  NEXT_PUBLIC_EVM_CHAIN_NAME: process.env.NEXT_PUBLIC_EVM_CHAIN_NAME,
  NEXT_PUBLIC_EVM_CHAIN_SHORT_NAME:
    process.env.NEXT_PUBLIC_EVM_CHAIN_SHORT_NAME,
  NEXT_PUBLIC_EVM_RPC_URL: process.env.NEXT_PUBLIC_EVM_RPC_URL,
  NEXT_PUBLIC_EVM_EXPLORER_NAME: process.env.NEXT_PUBLIC_EVM_EXPLORER_NAME,
  NEXT_PUBLIC_EVM_EXPLORER_URL: process.env.NEXT_PUBLIC_EVM_EXPLORER_URL,
  NEXT_PUBLIC_EVM_NATIVE_CURRENCY_NAME:
    process.env.NEXT_PUBLIC_EVM_NATIVE_CURRENCY_NAME,
  NEXT_PUBLIC_EVM_NATIVE_CURRENCY_SYMBOL:
    process.env.NEXT_PUBLIC_EVM_NATIVE_CURRENCY_SYMBOL,
  NEXT_PUBLIC_EVM_NATIVE_CURRENCY_DECIMALS:
    process.env.NEXT_PUBLIC_EVM_NATIVE_CURRENCY_DECIMALS,
  NEXT_PUBLIC_EVM_IS_TESTNET: process.env.NEXT_PUBLIC_EVM_IS_TESTNET,
  NEXT_PUBLIC_X402_NETWORK: process.env.NEXT_PUBLIC_X402_NETWORK,
  NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS:
    process.env.NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS,
  NEXT_PUBLIC_PAYMENT_TOKEN_NAME: process.env.NEXT_PUBLIC_PAYMENT_TOKEN_NAME,
  NEXT_PUBLIC_PAYMENT_TOKEN_SYMBOL:
    process.env.NEXT_PUBLIC_PAYMENT_TOKEN_SYMBOL,
  NEXT_PUBLIC_PAYMENT_TOKEN_LABEL: process.env.NEXT_PUBLIC_PAYMENT_TOKEN_LABEL,
  NEXT_PUBLIC_PAYMENT_TOKEN_VERSION:
    process.env.NEXT_PUBLIC_PAYMENT_TOKEN_VERSION,
  NEXT_PUBLIC_PAYMENT_TOKEN_DECIMALS:
    process.env.NEXT_PUBLIC_PAYMENT_TOKEN_DECIMALS,
  NEXT_PUBLIC_PAYMENT_TOKEN_TRANSFER_METHOD:
    process.env.NEXT_PUBLIC_PAYMENT_TOKEN_TRANSFER_METHOD,
  NEXT_PUBLIC_WALLET_PROVIDER: process.env.NEXT_PUBLIC_WALLET_PROVIDER
})
